"""Small-strain crystal-plasticity FEM solver (2D & 3D).

Uses the **initial-strain** (eigenstrain) formulation of small-strain
plasticity. The equilibrium at each load step is::

    K_elastic · u = F_ext(load) + F_plastic(state)

where ``F_plastic = ∫ B^T (C : ε_p) dV`` is the load vector generated by the
plastic strain (treated as an eigenstrain). Because ``K_elastic`` is constant
(the elastic stiffness does not depend on the plastic state), each step is a
single *linear* solve — the nonlinearity is entirely in the constitutive
update, which is advanced explicitly.

Algorithm per load step (advanced via ``jax.lax.scan`` for end-to-end AD)::

    1. Assemble  F_plastic  from the current per-quadrature-point plastic strain
    2. Solve     K_bc · u = load · F_body + F_plastic   (with Dirichlet BCs)
    3. Evaluate  ε  at every quadrature point from  u
    4. Update    state_qp  via the rate-dependent CP update (explicit sub-steps)

The whole time-stepping loop is differentiable: gradients propagate through
the linear solves, the strain evaluation, and the constitutive update, so one
can optimise material parameters (``E``, ``g0``, ``h0``, …) against a final
displacement or strain-energy objective with ``jax.grad``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import jax
import jax.numpy as jnp
import numpy as np

from diffmech.core import (
    Mesh, gauss_legendre_nd, get_shape_function, physical_gradient_and_det,
)
from diffmech.materials import LinearElasticIsotropic
from diffmech.methods.fem.linear_fem import assemble_stiffness, _assemble_body_force
from diffmech.solvers.boundary_conditions import DirichletBC

from diffmech.methods.cpfe.crystal_plasticity import (
    CrystalPlasticity, CPState, cp_update,
)


@dataclass(frozen=True)
class CPFEProblem:
    """Specification of a small-strain crystal-plasticity FEM problem.

    Attributes
    ----------
    mesh : Mesh
    material : CrystalPlasticity
    dirichlet_bcs : tuple of DirichletBC
        Base Dirichlet constraints; their prescribed values are scaled by the
        per-step ``load_factor`` (so a clamped BC with value 0 stays 0, while a
        ramped displacement BC with value ``u_target`` is applied as
        ``load_factor * u_target``).
    body_force : (dim,) array or None
        Base body force, scaled by ``load_factor`` each step.
    dim : int or None
        Spatial dimension (defaults to ``mesh.dim``).
    """

    mesh: Mesh
    material: CrystalPlasticity
    dirichlet_bcs: tuple = field(default_factory=tuple)
    body_force: jnp.ndarray | None = None
    dim: int | None = None

    @property
    def n_dofs(self) -> int:
        dim = self.dim or self.mesh.dim
        return self.mesh.n_nodes * dim


@dataclass(frozen=True)
class CPFESolution:
    """Result of a CPFE solve."""

    u: jnp.ndarray              # (n_dofs,) final nodal displacements
    state: CPState             # per-QP state (batched over n_cells * n_qp)
    u_history: jnp.ndarray     # (n_steps, n_dofs) displacement at each step


# ---------------------------------------------------------------------------
# Geometry pre-computation
# ---------------------------------------------------------------------------
def _quadrature_for(cell_type: str):
    if cell_type == "tri3":
        return gauss_legendre_nd(2, 2, reference="tri")
    if cell_type == "quad4":
        return gauss_legendre_nd(2, 2, reference="quad")
    if cell_type == "tet4":
        return gauss_legendre_nd(2, 3, reference="tet")
    if cell_type == "hex8":
        return gauss_legendre_nd(2, 3, reference="hex")
    raise ValueError(f"unsupported cell_type {cell_type!r}")


def _precompute_geometry(mesh: Mesh, dim: int):
    """Precompute ``dN/dx``, ``detJ`` and weights for every (cell, QP) pair.

    Returns
    -------
    dN_dx : (n_cells, n_qp, n_nodes, dim)
    detJ : (n_cells, n_qp)
    weights : (n_qp,)
    """
    sf = get_shape_function(mesh.cell_type)
    qr = _quadrature_for(mesh.cell_type)
    n_qp = qr.n_points
    cell_coords = mesh.cell_coords  # (n_cells, n_nodes, dim)

    def cell_geom(coords):
        def qp_geom(xi_w):
            xi, w = xi_w
            dN_dxi = sf.grad(xi)
            dN_dx, detJ = physical_gradient_and_det(dN_dxi, coords)
            return dN_dx, detJ
        return jax.vmap(qp_geom)((qr.points, qr.weights))

    dN_dx, detJ = jax.vmap(cell_geom)(cell_coords)  # (n_cells,n_qp,n_nodes,dim),(n_cells,n_qp)
    return dN_dx, detJ, qr.weights


# ---------------------------------------------------------------------------
# Strain evaluation at all QPs
# ---------------------------------------------------------------------------
def _gather_u_per_cell(U: jnp.ndarray, cells: jnp.ndarray, dim: int) -> jnp.ndarray:
    """Gather nodal displacements for each cell → (n_cells, n_nodes, dim)."""
    n_dpc = cells.shape[1]

    def cell_u(cell):
        dofs = jnp.repeat(cell * dim, dim) + jnp.tile(jnp.arange(dim), n_dpc)
        return U[dofs].reshape(n_dpc, dim)

    return jax.vmap(cell_u)(cells)


def _compute_qp_strains(
    dN_dx: jnp.ndarray, u_per_cell: jnp.ndarray
) -> jnp.ndarray:
    """Small-strain tensor at every QP.

    Parameters
    ----------
    dN_dx : (n_cells, n_qp, n_nodes, dim)
    u_per_cell : (n_cells, n_nodes, dim)

    Returns
    -------
    eps : (n_cells, n_qp, dim, dim)
    """
    # grad_u[e,q,a,b] = sum_i u[e,i,a] * dN_dx[e,q,i,b]
    grad_u = jnp.einsum("eia,eqib->eqab", u_per_cell, dN_dx)
    return 0.5 * (grad_u + jnp.transpose(grad_u, (0, 1, 3, 2)))


# ---------------------------------------------------------------------------
# Plastic load vector assembly
# ---------------------------------------------------------------------------
def _assemble_plastic_force(
    dN_dx: jnp.ndarray,
    detJ: jnp.ndarray,
    weights: jnp.ndarray,
    eps_p_qp: jnp.ndarray,
    mat: CrystalPlasticity,
    mesh: Mesh,
    dim: int,
) -> jnp.ndarray:
    """Assemble ``F_plastic = ∫ B^T (C : ε_p) dV``.

    Parameters
    ----------
    eps_p_qp : (n_cells, n_qp, dim, dim) plastic strain at each QP
    """
    lam, mu = mat.lam, mat.mu
    eye = jnp.eye(dim, dtype=eps_p_qp.dtype)
    tr_p = jnp.trace(eps_p_qp, axis1=-2, axis2=-1)           # (n_cells, n_qp)
    sigma_p = lam * tr_p[..., None, None] * eye + 2.0 * mu * eps_p_qp  # (n_cells,n_qp,dim,dim)
    # f[e,q,i,a] = w[q] * detJ[e,q] * sum_b sigma_p[a,b] * dN_dx[i,b]
    f_qp = weights[None, :, None, None] * detJ[:, :, None, None] * \
        jnp.einsum("eqab,eqib->eqia", sigma_p, dN_dx)        # (n_cells,n_qp,n_nodes,dim)
    f_e = jnp.sum(f_qp, axis=1)                              # (n_cells, n_nodes, dim)
    f_e_flat = f_e.reshape(mesh.n_cells, -1)                 # (n_cells, n_nodes*dim)

    cells = mesh.cells
    n_dpc = mesh.nodes_per_cell
    n_dofs = mesh.n_nodes * dim

    def assemble_one(carry, args):
        fe, cell = args
        dofs = jnp.repeat(cell * dim, dim) + jnp.tile(jnp.arange(dim), n_dpc)
        return carry.at[dofs].add(fe), None

    F, _ = jax.lax.scan(assemble_one, jnp.zeros(n_dofs, dtype=U_dtype(eps_p_qp)),
                        (f_e_flat, cells))
    return F


def U_dtype(*arrays):
    """Pick a floating dtype from example arrays."""
    for a in arrays:
        if hasattr(a, "dtype"):
            return jnp.result_type(a)
    return jnp.float64


# ---------------------------------------------------------------------------
# Dirichlet BC application (jit-friendly, row+column elimination)
# ---------------------------------------------------------------------------
def _apply_dirichlet_K(K: jnp.ndarray, bc_dofs: jnp.ndarray) -> jnp.ndarray:
    """Zero BC rows/columns and set BC diagonal entries to 1 (identity rows)."""
    n = K.shape[0]
    mask = jnp.ones(n, dtype=K.dtype)
    mask = mask.at[bc_dofs].set(0.0)
    K = K * mask[:, None] * mask[None, :]
    diag = jnp.zeros(n, dtype=K.dtype)
    diag = diag.at[bc_dofs].set(1.0)
    return K + jnp.diag(diag)


# ---------------------------------------------------------------------------
# Main solver
# ---------------------------------------------------------------------------
def solve_cpfe(
    problem: CPFEProblem,
    load_factors: jnp.ndarray,
    *,
    dt: float = 1.0,
    n_sub: int = 1,
    return_history: bool = False,
) -> CPFESolution:
    """Solve the small-strain rate-dependent CPFE problem.

    Parameters
    ----------
    problem : CPFEProblem
    load_factors : (n_steps,) array
        Per-step load multiplier. Ramps from 0→1 for a standard proportional
        loading. Both the body force and Dirichlet BC values are scaled by
        ``load_factor`` (so clamped BCs with value 0 remain 0).
    dt : float
        Time step used in the constitutive update (per load step).
    n_sub : int
        Number of constitutive sub-steps per load step (improves stability
        and accuracy of the explicit CP update).
    return_history : bool
        If True, store and return the displacement at every step.

    Returns
    -------
    CPFESolution
    """
    dim = problem.dim or problem.mesh.dim
    mesh = problem.mesh
    mat = problem.material
    n_dofs = mesh.n_nodes * dim
    n_cells = mesh.n_cells
    dtype = jnp.float64

    # --- precompute geometry (constant) -----------------------------------
    dN_dx, detJ, weights = _precompute_geometry(mesh, dim)
    n_qp = weights.shape[0]

    # --- elastic stiffness (constant) -------------------------------------
    lin_mat = LinearElasticIsotropic(E=mat.E, nu=mat.nu)
    K_elastic = assemble_stiffness(mesh, lin_mat, dim=dim)

    # --- body force (base, scaled by load_factor) -------------------------
    F_body = jnp.zeros(n_dofs, dtype=dtype)
    if problem.body_force is not None:
        F_body = _assemble_body_force(mesh, jnp.asarray(problem.body_force, dtype=dtype), dim=dim)

    # --- BC dofs / base values --------------------------------------------
    if problem.dirichlet_bcs:
        bc_dofs = jnp.concatenate([jnp.atleast_1d(bc.dofs) for bc in problem.dirichlet_bcs])
        bc_values_base = jnp.concatenate(
            [jnp.atleast_1d(bc.values).astype(dtype) for bc in problem.dirichlet_bcs]
        )
    else:
        bc_dofs = jnp.zeros(0, dtype=jnp.int32)
        bc_values_base = jnp.zeros(0, dtype=dtype)

    K_bc = _apply_dirichlet_K(K_elastic, bc_dofs)

    # --- initial per-QP state ---------------------------------------------
    state0 = mat.initial_state()
    shape_qp = (n_cells, n_qp)
    eps_p0 = jnp.broadcast_to(state0.eps_p, shape_qp + (dim, dim)).astype(dtype)
    gamma0 = jnp.broadcast_to(state0.gamma, shape_qp + (mat.n_slip,)).astype(dtype)
    g0 = jnp.broadcast_to(state0.g, shape_qp + (mat.n_slip,)).astype(dtype)
    state_qp0 = CPState(eps_p=eps_p0, gamma=gamma0, g=g0)

    u0 = jnp.zeros(n_dofs, dtype=dtype)
    cells = mesh.cells

    # --- time-stepping scan -----------------------------------------------
    def step(carry, load_factor):
        u_prev, state_qp = carry
        # 1. Plastic load from current state
        F_plastic = _assemble_plastic_force(
            dN_dx, detJ, weights, state_qp.eps_p, mat, mesh, dim
        )
        # 2. Total RHS = load * body_force + F_plastic
        F_rhs = load_factor * F_body + F_plastic
        # 3. Enforce Dirichlet BCs: set BC dofs to load_factor * base values
        F_rhs = F_rhs.at[bc_dofs].set(load_factor * bc_values_base)
        # 4. Linear solve (K_bc is constant, symmetric, SPD on free dofs)
        u_new = jnp.linalg.solve(K_bc, F_rhs)
        # 5. Strain at every QP
        u_per_cell = _gather_u_per_cell(u_new, cells, dim)
        eps_qp = _compute_qp_strains(dN_dx, u_per_cell)  # (n_cells, n_qp, dim, dim)
        # 6. Constitutive update (explicit, sub-stepped)
        def single(eps, st):
            return cp_update(eps, st, mat, dt, n_sub)
        state_new = jax.vmap(jax.vmap(single))(eps_qp, state_qp)
        return (u_new, state_new), u_new

    (u_final, state_final), u_history = jax.lax.scan(
        step, (u0, state_qp0), xs=load_factors,
    )
    if not return_history:
        u_history = jnp.zeros((0, n_dofs), dtype=dtype)
    return CPFESolution(u=u_final, state=state_final, u_history=u_history)


# ---------------------------------------------------------------------------
# Post-processing helpers
# ---------------------------------------------------------------------------
def qp_state_at_cell(
    state: CPState, cell_index: int, n_qp: int
) -> CPState:
    """Extract the per-QP state for a single cell (for post-processing)."""
    eps_p = state.eps_p[cell_index]    # (n_qp, dim, dim)
    gamma = state.gamma[cell_index]    # (n_qp, n_slip)
    g = state.g[cell_index]            # (n_qp, n_slip)
    return CPState(eps_p=eps_p, gamma=gamma, g=g)


def average_equivalent_plastic_strain(state: CPState) -> jnp.ndarray:
    """Volume-averaged equivalent plastic strain (scalar)."""
    eps_p = state.eps_p  # (..., dim, dim)
    # Equivalent plastic strain: eps_eq = sqrt(2/3 * eps_p_dev : eps_p_dev)
    dim = eps_p.shape[-1]
    eye = jnp.eye(dim, dtype=eps_p.dtype)
    tr = jnp.trace(eps_p, axis1=-2, axis2=-1)[..., None, None]
    eps_p_dev = eps_p - tr / dim * eye
    eps_eq = jnp.sqrt(2.0 / 3.0 * jnp.sum(eps_p_dev * eps_p_dev, axis=(-2, -1)))
    return jnp.mean(eps_eq)


def total_slip(state: CPState) -> jnp.ndarray:
    """Total accumulated slip summed over all systems and QPs."""
    return jnp.sum(jnp.abs(state.gamma))
